---
title: "Benjamin's CV"
author: Benjamin Mercier
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/styles.css', 'resume', 'https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css']
    self_contained: true
---

```{r, include=FALSE, cache = F}
knitr::opts_chunk$set(
  results='asis',
  echo = FALSE
)

library(glue)
library(tidyverse)


# Holds all the links that were inserted for placement at the end
PDF_EXPORT <- FALSE

source('R/parsing_functions.R')

# Load csv with position info
position_data <- readr::read_csv('data/positions.csv')
```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> benjamin.b.mercier@usherbrooke.ca
- <i class="fa fa-twitter"></i> [BenMerSci](https://twitter.com/BenMerSci)
- <i class="fa fa-github"></i> [BenMerSci](https://github.com/BenMerSci)
- <i class="ai ai-google-scholar"></i> [Publications](https://scholar.google.com/citations?user=GyChlIoAAAAJ&hl=en)
- <i class="ai ai-orcid"></i> [0000-0002-4104-9463](https://orcid.org/0000-0002-4104-9463)


Quantitative skills
------------------------------------

Regression, Basic knowledge in different modelling techniques (RandomForest, SDM, JSDM)


Programming skills
------------------------------------

<span style="font-weight:600;">Data analysis</span>: <br>R - 60%, <br>Julia - 15%<br>

<span style="font-weight:600;">Data base</span>: SQLite (Basic knowledge)<br>

<span style="font-weight:600;">Automation/reports</span>: <br>Rmarkdown, Git, bash<br> 


Languages
------------------------------------

**French**<span style="font-size:11px;"> Native</span><br>
**English**<span style="font-size:11px;"> Full Professional</span><br>


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with [**pagedown**](https://github.com/rstudio/pagedown).

The source code is available at [github.com/BenMerSci/cv](https://github.com/BenMerSci/cv).

Last updated on `r Sys.Date()`.

[<i class='fas fa-download'></i> Download a PDF of this CV](https://willvieira.github.io/cv/BenMerSci.pdf)


Main
================================================================================

 <span style="font-weight:600">BenMerSci</span> <span style="font-size: 13px;">B.Sc. in Ecology</span>{#title}
--------------------------------------------------------------------------------


<span style="font-size: 1rem;">< <i class="fa fa-chart-bar"></i> + <i class="fa fa-robot"></i> >  Quantitative ecologist </span>


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```



Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'research_positions')
```


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'teaching_positions')
```

Training {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'training')
```


Publications {data-icon=book}
--------------------------------------------------------------------------------


```{r}
# TODO automate it
# Load publications from ORCID
#my_dois <- try(rorcid::identifiers(rorcid::works("0000-0003-0283-4570")))
#pubs <- rcrossref::cr_cn(dois = my_dois, format = "text")

# Add my name in bold and convert DOI in a link
#fixedPubs <- lapply(pubs, editRefs)

#print_section(position_data, 'training')
```

### Environmental biases in the study of ecological networks at the planetary scale

BioRxiv - PrePrint <a href="https://doi.org/10.1101/2020.01.27.921429"><i class="ai ai-doi"></i></a>

N/A

2020

- Poisot, T., Bergeron, G., Cazelles, K., Dallas, T., Gravel, D., Macdonald, A., Mercier, B., Violet, C., Vissault, S.


Selected Talks and Posters {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'talk_poster')
```
